artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL:  https://0x0.st/H31h.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/wine-quality.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/wine-quality.csv
  clean_data: artifacts/data_transformation/clean-wine-quality.csv


model_trainer:
  root_dir: artifacts/model_trainerw
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib